name: Access API
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
    paths:
      - 'packages/access-api/**'
      - '.github/workflows/access-api.yml'
      - 'pnpm-lock.yaml'
      - '.env.tpl'
  pull_request:
    paths:
      - 'packages/access-api/**'
      - '.github/workflows/access-api.yml'
      - 'pnpm-lock.yaml'
      - '.env.tpl'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/access-api run lint
      - run: pnpm -r --filter @web3-storage/access-api run test
  deploy-staging:
    needs: test
    if: github.head_ref == 'release-please--branches--main--components--access-api'
    uses: './.github/workflows/reuse-deploy-api.yml'
    with:
      environment: staging
      environment_url: https://w3access-staging.protocol-labs.workers.dev
    secrets: inherit
  deploy-dev:
    needs: test
    if: github.event_name == 'pull_request' && !contains(github.head_ref, 'release-please--branches')
    uses: './.github/workflows/reusable-deploy-api.yml'
    with:
      environment: dev
      environment_url: https://w3access-dev.protocol-labs.workers.dev
    secrets: inherit
