name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to deploy'
        required: true
        type: choice
        default: 'website'
        options:
          - website
          - api
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: 'staging'
        options:
          - production
          - staging
          - dev
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    if: github.event.inputs.package == 'website'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/wallet/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('packages/wallet/**.[jt]s', 'packages/wallet/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - run: pnpm install
      - run: pnpm -r --filter wallet run build
      # - name: Publish
      #   uses: cloudflare/wrangler-action@2.0.0
      #   with:
      #     apiToken: ${{ secrets.CF_TOKEN }}
      #     accountId: ${{ secrets.CF_ACCOUNT_ID }}
      #     command: pages publish --project-name=ucan-protocol ./packages/wallet/out
      - run: pnpm exec wrangler pages publish --project-name ucan-protocol --branch master ./packages/wallet/out
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  # deploy-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: pnpm/action-setup@v2.0.1
  #       with:
  #         version: 7
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 18
  #         cache: 'pnpm'
  #     - run: pnpm install
  #     # Publish worker to cloudflare
  #     - uses: cloudflare/wrangler-action@2.0.0
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         workingDirectory: 'packages/access-api'
