name: Reusable Deploy API
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_url:
        description: URL of the deployed environment. If provided, this will be added to the GitHub environment.
        required: false
        type: string
    secrets:
      CF_TOKEN:
        required: true
      POSTMARK_TOKEN:
        required: true
      PRIVATE_KEY:
        required: true
      SENTRY_DSN:
        required: true
      SENTRY_UPLOAD:
        required: true
      SENTRY_TOKEN:
        required: true
      LOGTAIL_TOKEN:
        required: true
      UCAN_LOG_BASIC_AUTH:
        required: true

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm --filter '@web3-storage/access-api...' install
      # release prep
      - id: set-release-name
        env:
          ENV: ${{ inputs.environment }}
        run: |
          echo "release_name=$(node packages/access-api/scripts/release.js)" >> "$GITHUB_OUTPUT"
      - run: echo "release name is ${{ steps.set-release-name.outputs.release_name }}"
      # Migration database
      - run: pnpm -r --filter @web3-storage/access-api exec wrangler d1 migrations apply __D1_BETA__ --env ${{ inputs.environment }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      # Publish worker to cloudflare
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          # preCommands: git config --global --add safe.directory "*"
          apiToken: ${{ secrets.CF_TOKEN }}
          workingDirectory: 'packages/access-api'
          environment: ${{ inputs.environment }}
          secrets: |
            POSTMARK_TOKEN
            PRIVATE_KEY
            SENTRY_DSN
            LOGTAIL_TOKEN
            UCAN_LOG_BASIC_AUTH
        env:
          POSTMARK_TOKEN: ${{ secrets.POSTMARK_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_UPLOAD: ${{ secrets.SENTRY_UPLOAD }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          LOGTAIL_TOKEN: ${{ secrets.LOGTAIL_TOKEN }}
          UCAN_LOG_BASIC_AUTH: ${{ secrets.UCAN_LOG_BASIC_AUTH }}
      - working-directory: packages/access-api
        run: |
          pnpm exec wrangler publish --dry-run --outdir=dist
          ls -alh dist
          echo "RELEASE_NAME=$RELEASE_NAME"
          echo "SENTRY_ORG=$SENTRY_ORG"
          echo "SENTRY_PROJECT=$SENTRY_PROJECT"
          pnpm exec -c sentry-cli releases new "$RELEASE_NAME" --finalize
          pnpm exec -c sentry-cli releases files "$RELEASE_NAME" upload-sourcemaps ./dist
        env:
          ENV: ${{ vars.ENV }}
          RELEASE_NAME: ${{ steps.set-release-name.outputs.release_name }}"
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
